
let devices = {
"0":{"id":"0","boardId":"0","name":"red_led","pin":"38","value":"n/a","mode":"output"},
"1":{"id":"1","boardId":"2","pin":"40","name":"green_led","value":"n/a","mode":"output"},
};
module.exports.devices = devices;

let board = {"1":{"id":"1","boardPin":"1","modes":"tbd","used":"n/a"},"2":{"id":"2","boardPin":"2","modes":"tbd","used":"n/a"},"3":{"id":"3","boardPin":"3","modes":"tbd","used":"n/a"},"4":{"id":"4","boardPin":"4","modes":"tbd","used":"n/a"},"5":{"id":"5","boardPin":"5","modes":"tbd","used":"n/a"},"6":{"id":"6","boardPin":"6","modes":"tbd","used":"n/a"},"7":{"id":"7","boardPin":"7","modes":"tbd","used":"n/a"},"8":{"id":"8","boardPin":"8","modes":"tbd","used":"n/a"},"9":{"id":"9","boardPin":"9","modes":"tbd","used":"n/a"},"10":{"id":"10","boardPin":"10","modes":"tbd","used":"n/a"},"11":{"id":"11","boardPin":"11","modes":"tbd","used":"n/a"},"12":{"id":"12","boardPin":"12","modes":"tbd","used":"n/a"},"13":{"id":"13","boardPin":"13","modes":"tbd","used":"n/a"},"14":{"id":"14","boardPin":"14","modes":"tbd","used":"n/a"},"15":{"id":"15","boardPin":"15","modes":"tbd","used":"n/a"},"16":{"id":"16","boardPin":"16","modes":"tbd","used":"n/a"},"17":{"id":"17","boardPin":"17","modes":"tbd","used":"n/a"},"18":{"id":"18","boardPin":"18","modes":"tbd","used":"n/a"},"19":{"id":"19","boardPin":"19","modes":"tbd","used":"n/a"},"20":{"id":"20","boardPin":"20","modes":"tbd","used":"n/a"},"21":{"id":"21","boardPin":"20","modes":"tbd","used":"n/a"},"22":{"id":"22","boardPin":"20","modes":"tbd","used":"n/a"},"23":{"id":"23","boardPin":"20","modes":"tbd","used":"n/a"},"24":{"id":"24","boardPin":"20","modes":"tbd","used":"n/a"},"25":{"id":"25","boardPin":"20","modes":"tbd","used":"n/a"},"26":{"id":"26","boardPin":"20","modes":"tbd","used":"n/a"},"27":{"id":"27","boardPin":"20","modes":"tbd","used":"n/a"},"28":{"id":"28","boardPin":"20","modes":"tbd","used":"n/a"},"29":{"id":"29","boardPin":"20","modes":"tbd","used":"n/a"},"30":{"id":"30","boardPin":"30","modes":"tbd","used":"n/a"},"31":{"id":"31","boardPin":"31","modes":"tbd","used":"n/a"},"32":{"id":"32","boardPin":"32","modes":"tbd","used":"n/a"},"33":{"id":"33","boardPin":"33","modes":"tbd","used":"n/a"},"34":{"id":"34","boardPin":"34","modes":"tbd","used":"n/a"},"35":{"id":"35","boardPin":"35","modes":"tbd","used":"n/a"},"36":{"id":"36","boardPin":"36","modes":"tbd","used":"n/a"},"37":{"id":"37","boardPin":"37","modes":"tbd","used":"n/a"},"38":{"id":"38","boardPin":"38","modes":"input/output","used":"n/a"},"39":{"id":"39","boardPin":"39","modes":"GND","used":"n/a"},"40":{"id":"40","boardPin":"40","modes":"input/output","used":"n/a"}};
module.exports.board = board;
